name: deploy-cd  

on: 
   push:
     branches: [main]
jobs:
  conventional-commit:
    name: "conventionnal commit"
    runs-on: ubuntu-latest
    steps:
    - name: "Affichaged'un message d'exemple "
      run: echo "Salutation"
    - name: "pull du git"
      uses: actions/checkout@v2
    - name: "installation de NodeJS version 14" 
      uses: actions/setup-node@v2
      with:
        fetch-depth: 0
        node-version: '14'
    - name: "Configuration de l'utilisateur git"
      run: 
       git config --local user.email "github-actions[bot]@users.noreply.github.com"
       git config --localh user.name "github-actions[bot]"
    - name: "création du CHANGELOG et du calcue de version"  
      run: npx standard-version 
    - name: "git push"   
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN}}
         branch: main       

  delivry:
    name: "build et push de l'image sur ACR"
    runs-on: ubuntu-latest
    #needs: conventional-commit:
    steps:
    - run: echo "hello world"